// User reducer types
export const SET_AUTH = "SET_AUTH";
export const SET_UNAUTH = "SET_UNAUTH";
export const SET_USER = "SET_USER";
export const SET_IMAGE_USER = "SET_IMAGE_USER";
export const LOADING_USER = "LOADING_USER";
export const LOADING_IMAGE = "LOADING_IMAGE";
export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";

// UI reducer types
export const SET_ERRORS = "SET_ERRORS";
export const SET_FLASH_MESSAGE = "SET_FLASH_MESSAGE";
export const UNSET_FLASH_MESSAGE = "UNSET_FLASH_MESSAGE";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

// Data reducer types
export const SET_STATUS = "SET_STATUS";
export const SET_AVAILABLE_COURSE = "SET_AVAILABLE_COURSE";
export const SET_SINGLE_COURSE = "SET_SINGLE_AVAILABLE_COURSE";
export const SET_MY_COURSE = "SET_MY_COURSE";
export const SET_FORUM = "SET_FORUM";
export const SET_SINGLE_FORUM = "SET_SINGLE_FORUM";
export const SET_COMMENT = "SET_COMMENT";
export const SET_LOADING_FORUM = "SET_LOADING_FORUM";
export const SET_LOADING_SINGLE_FORUM = "SET_LOADING_SINGLE_FORUM";
export const SET_LOADING_AVAILABLE_COURSE = "SET_LOADING_AVAILABLE";
export const SET_LOADING_SINGLE_COURSE = "SET_LOADING_SINGLE_COURSE";
export const SET_LOADING_MY_COURSE = "SET_LOADING_MY_COURSE";
export const STATUS_UPLOAD = "STATUS_UPLOAD";

// Data reducer admin
export const SET_COURSE_ADMIN = "SET_COURSE_ADMIN";
export const SET_MATERIAL_ADMIN = "SET_MATERIAL_ADMIN";
export const UNSET_MATERIAL_ADMIN = "UNSET_MATERIAL_ADMIN";
export const SET_ALL_ANSWER = "SET_ALL_ANSWER";
export const LOADING_COURSE_ADMIN = "LOADING_COURSE_ADMIN";
export const LOADING_MATERIAL_ADMIN = "LOADING_MATERIAL_ADMIN";
export const LOADING_STUDENTS = "LOADING_STUDENTS";
export const LOADING_LECTURERS = "LOADING_LECTURERS";
export const SET_STUDENTS = "SET_STUDENTS";
export const SET_LECTURERS = "SET_LECTURERS";
